/* Auto-generated by tools/gen_build_timestamp.py - do not hand-edit. */
#ifndef BUILD_TIMESTAMP_H
#define BUILD_TIMESTAMP_H

#define BUILD_TIMESTAMP_MADRID "Aug 20 2026 - 16:26:28 CEST"

#endif /* BUILD_TIMESTAMP_H */
