#!/usr/bin/env python3
"""Generate include/build_timestamp.h with the current build time in Madrid
(Europe/Madrid, CET/CEST) local time.

__DATE__/__TIME__ only reflect whatever local timezone the *build machine's*
OS happens to be set to, with no timezone label at all - this generates an
explicit, correctly-labeled Madrid timestamp instead, independent of the
build machine's own clock/timezone setting.

Run this before building (both the standalone Makefile and the S32DS IDE
pick it up automatically once generated, since it's just a regular header
in the existing include search path) to refresh the timestamp:

    python tools/gen_build_timestamp.py
"""
from datetime import datetime
from zoneinfo import ZoneInfo
import pathlib

now = datetime.now(ZoneInfo("Europe/Madrid"))
timestamp = now.strftime("%b %d %Y - %H:%M:%S %Z")

out_path = pathlib.Path(__file__).resolve().parent.parent / "include" / "build_timestamp.h"
out_path.write_text(
    "/* Auto-generated by tools/gen_build_timestamp.py - do not hand-edit. */\n"
    "#ifndef BUILD_TIMESTAMP_H\n"
    "#define BUILD_TIMESTAMP_H\n\n"
    f'#define BUILD_TIMESTAMP_MADRID "{timestamp}"\n\n'
    "#endif /* BUILD_TIMESTAMP_H */\n",
    newline="\n",
)
print(f"Wrote {out_path} : BUILD_TIMESTAMP_MADRID = \"{timestamp}\"")
